/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiTryonRouteImport } from './routes/api/tryon'
import { Route as ApiMyntraProductRouteImport } from './routes/api/myntra-product'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTryonRoute = ApiTryonRouteImport.update({
  id: '/api/tryon',
  path: '/api/tryon',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMyntraProductRoute = ApiMyntraProductRouteImport.update({
  id: '/api/myntra-product',
  path: '/api/myntra-product',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/myntra-product': typeof ApiMyntraProductRoute
  '/api/tryon': typeof ApiTryonRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/myntra-product': typeof ApiMyntraProductRoute
  '/api/tryon': typeof ApiTryonRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/myntra-product': typeof ApiMyntraProductRoute
  '/api/tryon': typeof ApiTryonRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/myntra-product' | '/api/tryon'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/myntra-product' | '/api/tryon'
  id: '__root__' | '/' | '/api/myntra-product' | '/api/tryon'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiMyntraProductRoute: typeof ApiMyntraProductRoute
  ApiTryonRoute: typeof ApiTryonRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tryon': {
      id: '/api/tryon'
      path: '/api/tryon'
      fullPath: '/api/tryon'
      preLoaderRoute: typeof ApiTryonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/myntra-product': {
      id: '/api/myntra-product'
      path: '/api/myntra-product'
      fullPath: '/api/myntra-product'
      preLoaderRoute: typeof ApiMyntraProductRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiMyntraProductRoute: ApiMyntraProductRoute,
  ApiTryonRoute: ApiTryonRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
